branches:
  - master
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: eslint
  - - '@semantic-release/release-notes-generator'
    - preset: eslint
  - - '@semantic-release/changelog'
    - changelogTitle: Paypal Invoices JS ChangeLog
  - '@semantic-release/github'
  - - '@semantic-release/git'
    - assets:
        - package.json
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
