#!/usr/bin/env bash

echo 'Pre-Commit Hook'

STAGED=$(git diff --name-only --diff-filter d --staged | grep -e '\.tsx\?$')

if [ -z "$STAGED" ]; then
  echo 'No staged sourcecode files. skipping linter and formatter.'
  exit 0
fi

pnpm eslint $STAGED || exit 1

echo '\n----------------------\n'
echo 'Formatting staged files:\n'
pnpm prettier --config .prettierrc.yaml -w $STAGED || exit 1

echo '\n----------------------\n'
echo 'Re-adding staged Files:\n' && echo $STAGED
git add $STAGED || exit 1
